name: Main Test

on:
  push:
  pull_request:
    branches: [main]
    types: [opened, reopened]
jobs:
    run-tests:
        runs-on: ubuntu-latest
        environment: test
        strategy:
          fail-fast: false
          matrix:
            python-version: [ "3.10", "3.11", "3.12" ]
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4

          - name: Install Python
            uses: actions/setup-python@v5
            with:
              python-version: ${{ matrix.python-version }}

          - name: Install Python Dependencies
            run: |
              curl -LsSf https://astral.sh/uv/install.sh | sh
              uv pip install --system --break-system-packages -r requirements.txt
              uv pip install --system --break-system-packages pytest pytest-cov pytest-github-report pytest-github-actions-annotate-failures

          - name: Run Unit Tests
            env:
              pytest_github_report: true
              pytest_verbosity: 2
            run: pytest -v --cov=src --cov-report=xml --cov-report=term-missing --color=yes tests/

    test-build-pypi:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4

          - name: Install Python
            uses: actions/setup-python@v5
            with:
              python-version: "3.10"

          - name: Install Twine and Build
            run: sudo pip install twine build

          - name: Create the distribution
            run: |
              git fetch --prune --unshallow --tags
              sudo python3 -m build
